using System.Collections.Immutable;
using Microsoft.CodeAnalysis.CSharp;

namespace Netprof.Generators;

internal class ProfileZonesWriter : IDisposable
{
    private readonly StringWriter _writer = new();
    private int _indentation;

    public void Write(string assemblyName, ImmutableArray<InvocationSourceLocation> locations)
    {
        WriteLine("// <auto-generated/>");
        WriteLine();
        WriteBlock("namespace System.Runtime.CompilerServices", () =>
        {
            WriteLine("[global::System.Diagnostics.Conditional(\"DEBUG\")]");
            WriteLine("[global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]");
            WriteBlock("sealed file class InterceptsLocationAttribute : global::System.Attribute", () =>
            {
                WriteLine("public InterceptsLocationAttribute(int version, string data) { }");
            });
        });
        WriteLine();
        WriteBlock("namespace Netprof", () =>
        {
            WriteLine("[global::System.Diagnostics.DebuggerNonUserCode]");
            WriteLine("[global::System.Diagnostics.DebuggerStepThrough]");
            WriteBlock("static file class ProfileZones", () =>
            {
                WriteLine($"private const string AssemblyName = {SymbolDisplay.FormatLiteral(assemblyName, quote: true)};");
                WriteLine();
                for (var i = 0; i < locations.Length; i += 1)
                {
                    WriteLine($"private const string Zone{i} = {SymbolDisplay.FormatLiteral(locations[i].CallSite, quote: true)};");
                }
                for (var i = 0; i < locations.Length; i += 1)
                {
                    WriteLine();
                    WriteLine($"{locations[i].InterceptsLocationAttribute}");
                    if (locations[i].IsAsync)
                    {
                        WriteLine($"public static AsyncZone EnterAsyncZone{i}() => Profiler.EnterAsyncZone(Zone{i}); // {locations[i].Location}");
                    }
                    else
                    {
                        WriteLine($"public static Zone EnterZone{i}() => Profiler.EnterZone(Zone{i}); // {locations[i].Location}");
                    }
                }
            });
        });
    }

    private void WriteLine(string line = "")
    {
        if (!string.IsNullOrEmpty(line))
        {
            for (var i = 0; i < _indentation; i += 1)
            {
                _writer.Write("    ");
            }
        }

        _writer.WriteLine(line);
    }

    private void WriteBlock(string header, Action action)
    {
        WriteLine(header);
        WriteLine("{");
        _indentation += 1;
        action.Invoke();
        _indentation -= 1;
        WriteLine("}");
    }

    public override string ToString() => _writer.ToString();

    public void Dispose()
    {
        _writer.Dispose();
    }
}
