using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Operations;

namespace Netprof.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class ZoneGenerator : IIncrementalGenerator
{
    private const string EnterZone = nameof(EnterZone);

    public void Initialize(IncrementalGeneratorInitializationContext initContext)
    {
        var syntaxProvider = initContext.SyntaxProvider.CreateSyntaxProvider(static (node, _) => IsEnterZoneInvocation(node), GetInvocationSourceLocation);
        initContext.RegisterSourceOutput(syntaxProvider.Where(static x => x != null).Select(static (x, _) => x!).Collect(), static (productionContext, locations) =>
        {
            // TODO(alex): Sort the locations so we get a stable zone index across rebuilds.
            var builder = new StringBuilder(1024 + (locations.Length * 320)); // NOTE(alex): (VERY) rough estimate of file size (I did not think too hard about this). Main point is that file size is O(N + C), where C is header size.
            var assemblyName = typeof(ZoneGenerator).Assembly.GetName();
            builder.AppendLine(
                $$"""
                // <auto-generated/>
                #nullable enable

                namespace System.Runtime.CompilerServices
                {
                    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]
                    file sealed class InterceptsLocationAttribute : global::System.Attribute
                    {
                        public InterceptsLocationAttribute(int version, string data) { }
                    }
                }

                namespace Netprof
                {
                    /// <summary>
                    /// Contains metadata for the profiling zones generated for this assembly.
                    /// </summary>
                    internal static class ZoneRegistry
                    {
                        internal const int ZoneCount = {{locations.Length}};

                        [global::System.Runtime.CompilerServices.ModuleInitializer]
                        internal static void Initialize()
                        {
                            global::Netprof.Profiler.RegisterGeneratedZoneCount(ZoneCount);
                        }
                    }

                    /// <summary>
                    /// Contains compiler-generated interceptors that map profiling call sites to their corresponding counter indices.
                    /// </summary>
                    internal static class ZoneInterceptors
                    {
                """
            );
            for (var i = 0; i < locations.Length; i += 1)
            {
                var location = locations[i];
                builder.AppendLine(
                    $$"""
                                [global::System.Runtime.CompilerServices.InterceptsLocation({{location.Version}}, "{{location.Data}}")]
                                public static global::Netprof.Zone EnterZone{{i}}(this global::Netprof.Profiler profiler) => profiler.EnterZone({{i}});
                        """);
            }
            builder.AppendLine("    }");
            builder.AppendLine("}");
            productionContext.AddSource("Netprof.Generated.g.cs", builder.ToString());
        });
    }

    private static bool IsEnterZoneInvocation(SyntaxNode node)
    {
        // NOTE(alex): First, check if the node is a method call with no arguments.
        if (node is not InvocationExpressionSyntax invocation ||
            invocation.ArgumentList.Arguments.Count != 0)
        {
            return false;
        }

        // NOTE(alex): Then, check to see if it is the correct method (by name for now, by global symbol later):
        switch (invocation.Expression)
        {
            case MemberAccessExpressionSyntax memberAccess:
                return memberAccess.Name.Identifier.ValueText == EnterZone;

            case IdentifierNameSyntax identifier:
                return identifier.Identifier.ValueText == EnterZone;

            default:
                return false;
        }
    }

    private static InterceptableLocation? GetInvocationSourceLocation(GeneratorSyntaxContext context, CancellationToken cancellationToken)
    {
        var invocation = (InvocationExpressionSyntax)context.Node;
        var symbolInfo = context.SemanticModel.GetSymbolInfo(invocation, cancellationToken);

        // NOTE(alex): Now that we have the actual semantic model of the syntax node, ensure we are calling the correct method.
        if (symbolInfo.Symbol is not IMethodSymbol method ||
            method.Name != EnterZone ||
            method.Parameters.Length != 0 ||
            method.IsStatic || // TODO(alex): Should we make it static?
            method.ContainingType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) != "global::Netprof.Profiler")
        {
            return null;
        }

        return context.SemanticModel.GetInterceptableLocation(invocation, cancellationToken);
    }
}
